
- name: remove running broker
  docker:
    image: brokerage
    name: broker-con
    state: absent

- name: bootstrap users
  command: docker run --rm --net="host" -v /brokerage/broker_vol:/config brokerage python3 -m brokerage.tools.add_user -c /config/config.yml -u {{item.name}} -p {{item.pass}} -a {{item.admin}} -b {{item.balance}}
  with_items: BROKER_USERS
  
- name: bootstrap stocks
  command: docker run --rm --net="host" -v /brokerage/broker_vol:/config brokerage python3 -m brokerage.tools.add_stock -c /config/config.yml -s {{item.tick}} -p {{item.price}} -n {{item.name}}
  with_items: BROKER_STOCKS


- name: charlie flag
  command: docker run --rm --net="host" -v /banking/web_vol:/config banking python3 -m banking.tools.flag -c /config/config.yml -f "{{ FLAG_WEB_DB }}" 
