
- name: place root flag
  template:
    src: ../templates/team4_brokerage-root.j2
    dest: "/root/team4_brokerage-root.flag"
    mode: 0600
  
- name: Install java
  apt: name=openjdk-7-jdk

- name: Install python mysql required library
  apt: name=python-mysqldb

- name: Install mysql
  apt: name=mysql-server

- name: make sure mysql is running
  service:
    name: mysql
    state: started
    enabled: true

- name: configure the root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ MYSQL_ROOT_PW }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PW }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - www2.team4.isucdc.com

- name: ensure the web server database
  mysql_db:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PW }}"
    name: brokerage
    state: present
  notify:
    - bootstrap users
    - charlie flag

- name: configure the database broker account
  mysql_user:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PW }}"
    name: "{{ MYSQL_BROKERAGE_USER }}"
    password: "{{ MYSQL_BROKERAGE_PW }}"
    state: present
    priv: "brokerage.*:ALL"


- name: ensure directory exists
  file: path="/brokerage/brokerage" state=directory mode=0750

- name: copy the setup file
  copy:
    src: "../../../../brokerage/setup.py"
    dest: "/brokerage/brokerage/"
    force: yes
    mode: 0750

- name: copy the static file manifest
  copy:
    src: "../../../../brokerage/MANIFEST.in"
    dest: "/brokerage/brokerage/"
    force: yes
    mode: 0750

- name: copy the banking module source
  synchronize:
    src: "../../../../brokerage/brokerage"
    dest: "/brokerage/brokerage/"
    recursive: yes
    # rsync_path: "sudo rsync"


- name: copy the docker file over
  copy:
    src: "../../../../brokerage/Dockerfile"
    dest: "/brokerage/"

- name: pull latest ubuntu images
  docker:
    image: "ubuntu:14.04"

- name: ensure volume directory
  file: path="/brokerage/broker_vol" state=directory mode=0750

- name: copy configuration file over with parameters
  template:
    src: ../templates/config.j2
    dest: /brokerage/broker_vol/config.yml
    mode: 0750

- name: build docker file
  command: docker build -t brokerage . chdir=/brokerage/
  notify:
    - remove running broker

- meta: flush_handlers

- name: ensure container for web is running
  docker:
    image: brokerage
    net: host
    hostname: www
    name: broker-con
    restart_policy: always
    volumes:
      - "/brokerage/broker_vol:/config"


