- name: splunk_boot
  command:  /opt/splunk/forwarder/bin/splunk enable boot-start
- name: splunk forward
  command: /opt/splunkforwarder/bin/splunk add forward-server {{ splunk_host }}:{{ splunk_port }}
