router_iface_internal: 
  - name: internalnet
    iface: eth1

router_iface_external: 
  - name: WEB
    iface: eth0:0
  - name: WEB2
    iface: eth0:1
  - name: AD
    iface: eth0:2
  - name: RDP
    iface: eth0:3

external_ip:
  - name: EWEB1
    address: 200.2.96.50
    internal: 192.169.1.50
    port:
    - 80
  - name: EAD
    address: 200.2.96.40
    internal: 192.168.1.40
  - name: ERDP
    address: 200.2.96.30
    internal: 192.168.1.30
    port:
    - 3389
  - name: EWEB2
    address: 200.2.96.110

internal_ip:
  - name: IWEB1
    address: 192.168.1.50
  - name: IAD
    address: 192.168.1.40
  - name: IRDP
    address: 192.168.1.30
  - name: IWEB2
    address: 192.168.1.110
  - name: IDS
    address: 192.168.1.131

web_external:
  - name: EWEB1
    address: 200.2.96.50
  - name: EWEB2
    address: 200.2.96.110

web_internal:
  - name: IWEB1
    address: 192.168.1.50
  - name: IWEB2
    address: 192.168.1.110
