router_iface_internal: 
  - name: internalnet
    iface: eth1

router_configuration:
  - name: WEB
    iface: eth0
    external_name: EWEB
    internal_name: IWEB
    address: 200.2.96.50
    internal: 192.168.1.50
    exposed_port:
    - 80
    - 22
    internal_port:
    - 80
    
  - name: AD
    iface: eth0:0
    external_name: EAD
    internal_name: IAD
    address: 200.2.96.40
    internal: 192.168.1.40
    exposed_port:
    - 389
    - 3268
    exposed_udp:
    - 53
    - 389
    - 3268
    
  - name: RDP
    iface: eth0:2
    external_name: EAD
    internal_name: IAD
    address: 200.2.96.30
    internal: 192.168.1.30
    exposed_port:
    - 3389
    internal_port:
    - 3389
    exposed_udp:
    - 3389
    
  - name: WEB2
    iface: eth0:1
    external_name: EWEB2
    internal_name: IWEB2
    address: 200.2.96.110
    internal: 192.168.1.110
    exposed_port:
    - 80
    - 22
    internal_port:
    - 80
  - name: MASTER
    iface: eth0:3
    external_name: EMASTER
    internal_name: IMASTER
    address: 200.2.96.100
    internal: 192.168.1.100
    exposed_port:
    - 22
    internal_port:
    - 22

internal_ip:
  - name: IDS
    address: 192.168.1.131


