router_iface_internal: 
  - name: internalnet
    iface: eth1

router_configuration:
  - name: WEB
    iface: eth0
    external_name: EWEB
    internal_name: IWEB
    address: 200.2.96.50
    internal: 192.169.1.50
    exposed_port:
    - 80
    internal_port:
    - 80
    
  - name: AD
    iface: eth0:0
    external_name: EAD
    internal_name: IAD
    address: 200.2.96.40
    internal: 192.168.1.40
    
  - name: RDP
    iface: eth0:2
    external_name: EAD
    internal_name: IAD
    address: 200.2.96.30
    internal: 192.168.1.30
    exposed_port:
    - 3389
    internal_port:
    - 3389
    
  - name: WEB2
    iface: eth0:1
    external_name: EWEB2
    internal_name: IWEB2
    address: 200.2.96.110
    internal: 192.168.1.110
    exposed_port:
    - 80
    internal_port:
    - 80

internal_ip:
  - name: IDS
    address: 192.168.1.131


