---
- hosts: localhost
  tasks:
  - name: deplay firewall vm
    vsphere_guest:
      vcenter_hostname: 172.22.0.20
      username: Administrator@VSPHERE.LOCAL
      password: "#MahB0y!!"
      guest: firewall
      from_template: yes
      template_src: "ubuntu14.04_template"
      cluster: main
#     resource_pool: "main/primary"
