
- name: Install python mysql required library
  apt: name=python-mysqldb

- name: Install mysql
  apt: name=mysql-server

- name: make sure mysql is running
  service:
    name: mysql
    state: started
    enabled: true

- name: configure the root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ MYSQL_ROOT_PW }}"
    login_user: root
    login_password: "{{ MYSQL_ROOT_PW }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: ensure the web server database
  mysql_db:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PW }}"
    name: banking
    state: present
  notify:
    - bootstrap users
    - bootstrap transactions

- name: configure the web account
  mysql_user:
    login_user: root
    login_password: "{{ MYSQL_ROOT_PW }}"
    name: "{{ MYSQL_WEB_USER }}"
    password: "{{ MYSQL_WEB_PW }}"
    state: present
    priv: "banking.*:ALL"


- name: ensure directory exists
  file: path="/root/banking/" state=directory

- name: copy the setup file
  copy:
    src: "../../../../banking/setup.py"
    dest: "/root/banking/"
    force: yes

- name: copy the static file manifest
  copy:
    src: "../../../../banking/MANIFEST.in"
    dest: "/root/banking/"
    force: yes

- name: copy the banking module source
  synchronize:
    src: "../../../../banking/banking"
    dest: "/root/banking/"
    recursive: yes
    # rsync_path: "sudo rsync"


- name: copy the docker file over
  copy:
    src: "../../../../banking/Dockerfile"
    dest: "/root/"

- name: pull latest ubuntu images
  docker:
    image: "ubuntu:14.04"

- name: ensure volume directory
  file: path="/root/web_vol" state=directory mode=0600

- name: copy configuration file over with parameters
  template:
    src: ../templates/config.j2
    dest: /root/web_vol/config.yml
    mode: 0600

- name: build docker file
  command: docker build -t banking . chdir=/root/
  notify:
    - remove running web

- meta: flush_handlers

- name: ensure container for web is running
  docker:
    image: banking
    net: host
    hostname: www
    name: banking-web
    restart_policy: always
    volumes:
      - "/root/web_vol:/config"


